import Foundation
import Supabase

class SupabaseService {
    static let shared = SupabaseService()

    private let supabase: SupabaseClient

    private init() {
        guard let path = Bundle.main.path(forResource: "Supabase-Keys", ofType: "plist"),
              let keys = NSDictionary(contentsOfFile: path),
              let supabaseURLString = keys["SUPABASE_URL"] as? String,
              let supabaseKey = keys["SUPABASE_KEY"] as? String,
              let supabaseURL = URL(string: supabaseURLString) else {
            fatalError("Supabase-Keys.plist not found or is invalid.")
        }
        
        supabase = SupabaseClient(supabaseURL: supabaseURL, supabaseKey: supabaseKey)
    }

    // --- Session Operations ---

    /// Fetches all sessions from the 'time' table, sorted by arrival time.
    func fetchSessions() async throws -> [UsageSession] {
        let response: [UsageSession] = try await supabase.from("time").select().execute().value
        return response.sorted { $0.arrive_at > $1.arrive_at }
    }

    /// Creates a new session by inserting a record with the current arrival time.
    /// Returns the newly created session.
    @discardableResult
    func startNewSession() async throws -> UsageSession {
        let newSession = PartialUsageSession(arrive_at: Date())
        let response: [UsageSession] = try await supabase.from("time").insert(newSession).select().execute().value
        guard let createdSession = response.first else {
            throw NSError(domain: "SupabaseServiceError", code: 0, userInfo: [NSLocalizedDescriptionKey: "Failed to decode new session."])
        }
        return createdSession
    }

    /// Ends the current active session (the one without a leave_at time).
    /// Returns the updated session.
    @discardableResult
    func endCurrentSession() async throws -> UsageSession? {
        // Find the current open session
        let openSessions: [UsageSession] = try await supabase.from("time")
            .select()
            .is("leave_at", value: nil)
            .order("arrive_at", ascending: false)
            .limit(1)
            .execute().value

        guard let currentSession = openSessions.first else {
            // No open session found, which might be a valid state.
            print("No active session to end.")
            return nil
        }
        
        // Update it with the leave time
        let updatedSession = PartialUsageSession(leave_at: Date())
        let response: [UsageSession] = try await supabase.from("time")
            .update(updatedSession)
            .eq("id", value: currentSession.id)
            .select()
            .execute().value
        
        return response.first
    }
    
    /// Creates a complete, manually entered session.
    func addManualSession(arriveAt: Date, leaveAt: Date) async throws {
        let manualSession = PartialUsageSession(arrive_at: arriveAt, leave_at: leaveAt)
        try await supabase.from("time").insert(manualSession).execute()
    }

    /// Deletes a session by its ID.
    func deleteSession(id: Int) async throws {
        try await supabase.from("time").delete().eq("id", value: id).execute()
    }
    
    // MARK: - Member Operations (Supabase)

    // For inserting a new member, where `id` is generated by the DB.
    private struct MemberInsert: Encodable {
        var name: String
        var remarks: String?
        var is_active: Bool = true
    }

    func fetchMembers() async throws -> [Member] {
        try await supabase.from("members").select().order("created_at", ascending: false).execute().value
    }

    func addMember(name: String, remarks: String?) async throws -> Member {
        let newMember = MemberInsert(name: name, remarks: remarks)
        let response: [Member] = try await supabase.from("members").insert(newMember, returning: .representation).select().execute().value
        guard let createdMember = response.first else {
            throw NSError(domain: "Supabase", code: 0, userInfo: [NSLocalizedDescriptionKey: "Failed to decode created member."])
        }
        return createdMember
    }

    func updateMemberStatus(memberId: Int, isActive: Bool) async throws {
        try await supabase.from("members").update(["is_active": isActive]).eq("member_id", value: memberId).execute()
    }

    func deleteMember(memberId: Int) async throws {
        try await supabase.from("members").delete().eq("member_id", value: memberId).execute()
    }

    // MARK: - Payment Record Operations (Supabase)

    // For inserting a new payment record.
    private struct PaymentRecordInsert: Encodable {
        var member_id: Int
        var payment_date: Date
        var amount: Double
        var remarks: String?
    }

    func fetchAllPaymentRecords() async throws -> [PaymentRecord] {
        try await supabase.from("payment_records")
            .select("*, members(*)")
            .order("payment_date", ascending: false)
            .execute().value
    }
    
    func fetchPaymentRecords(for memberId: Int) async throws -> [PaymentRecord] {
        try await supabase.from("payment_records")
            .select("*, members(*)")
            .eq("member_id", value: memberId)
            .order("payment_date", ascending: false)
            .execute().value
    }

    func addPaymentRecord(memberId: Int, date: Date, amount: Double, remarks: String?) async throws -> PaymentRecord {
        let newRecord = PaymentRecordInsert(member_id: memberId, payment_date: date, amount: amount, remarks: remarks)
        let response: [PaymentRecord] = try await supabase.from("payment_records").insert(newRecord, returning: .representation).select().execute().value
        guard let createdRecord = response.first else {
            throw NSError(domain: "Supabase", code: 0, userInfo: [NSLocalizedDescriptionKey: "Failed to decode created payment record."])
        }
        return createdRecord
    }

    func deletePaymentRecord(paymentId: Int) async throws {
        try await supabase.from("payment_records").delete().eq("payment_id", value: paymentId).execute()
    }

    // MARK: - Expense Record Operations (Supabase)

    private struct ExpenseRecordInsert: Encodable {
        var type: ExpenseType
        var amount: Double
        var expense_date: Date
        var notes: String?
    }

    func fetchAllExpenseRecords() async throws -> [ExpenseRecord] {
        try await supabase.from("expense_records").select().order("expense_date", ascending: false).execute().value
    }

    func addExpenseRecord(type: ExpenseType, amount: Double, date: Date, notes: String?) async throws -> ExpenseRecord {
        let newRecord = ExpenseRecordInsert(type: type, amount: amount, expense_date: date, notes: notes)
        let response: [ExpenseRecord] = try await supabase.from("expense_records").insert(newRecord, returning: .representation).select().execute().value
        guard let createdRecord = response.first else {
            throw NSError(domain: "Supabase", code: 0, userInfo: [NSLocalizedDescriptionKey: "Failed to decode created expense record."])
        }
        return createdRecord
    }

    func deleteExpenseRecord(expenseId: Int) async throws {
        try await supabase.from("expense_records").delete().eq("expense_id", value: expenseId).execute()
    }
}

// A helper struct for partial updates/inserts
fileprivate struct PartialUsageSession: Codable {
    var arrive_at: Date? = nil
    var leave_at: Date? = nil
} 